# Generated by Django 5.2.14 on 2026-06-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("prazo", models.DateTimeField(verbose_name="Prazo")),
                ("prioridade", models.CharField(choices=[("BAIXA", "Baixa"), ("NORMAL", "Normal"), ("ALTA", "Alta"), ("CRITICA", "Crítica")], default="NORMAL", max_length=20, verbose_name="Prioridade")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tarefas_pessoais", to=settings.AUTH_USER_MODEL, verbose_name="Usuário")),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["prazo", "-criado_em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TarefaHistorico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tipo_evento", models.CharField(choices=[("CRIACAO", "Criação"), ("EDICAO", "Edição"), ("ALTERACAO_PRAZO", "Alteração de prazo"), ("COMENTARIO", "Comentário"), ("ANEXO", "Anexo")], max_length=20, verbose_name="Tipo de evento")),
                ("titulo_evento", models.CharField(max_length=200, verbose_name="Título do evento")),
                ("descricao_evento", models.TextField(blank=True, verbose_name="Descrição do evento")),
                ("comentario", models.TextField(blank=True, verbose_name="Comentário")),
                ("arquivo", models.FileField(blank=True, upload_to="tarefas/historico/", verbose_name="Arquivo")),
                ("nome_arquivo", models.CharField(blank=True, max_length=255, verbose_name="Nome do arquivo")),
                ("prazo_anterior", models.DateTimeField(blank=True, null=True, verbose_name="Prazo anterior")),
                ("prazo_novo", models.DateTimeField(blank=True, null=True, verbose_name="Prazo novo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("autor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tarefas_historicos", to=settings.AUTH_USER_MODEL, verbose_name="Autor")),
                ("tarefa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="historico", to="tarefas.tarefa", verbose_name="Tarefa")),
            ],
            options={
                "verbose_name": "Histórico da tarefa",
                "verbose_name_plural": "Históricos das tarefas",
                "ordering": ["-criado_em", "-id"],
            },
        ),
    ]
