# Generated by OpenAI Codex on 2026-06-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preencher_criado_por(apps, schema_editor):
    Tarefa = apps.get_model("tarefas", "Tarefa")
    for tarefa in Tarefa.objects.filter(criado_por__isnull=True).exclude(responsavel__isnull=True):
        tarefa.criado_por_id = tarefa.responsavel_id
        tarefa.save(update_fields=["criado_por"])


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarefa",
            old_name="usuario",
            new_name="responsavel",
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas_responsavel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsável",
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas_criadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="concluida_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Concluída em"),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("CONCLUIDA", "Concluída"),
                    ("ARQUIVADA", "Arquivada"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.RunPython(preencher_criado_por, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tarefa",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tarefas_criadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
    ]
