# Generated by OpenAI Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0002_tarefa_status_campos_pessoais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefahistorico",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Criação"),
                    ("EDICAO", "Edição"),
                    ("ALTERACAO_PRAZO", "Alteração de prazo"),
                    ("ALTERACAO_STATUS", "Alteração de status"),
                    ("CONCLUSAO", "Conclusão"),
                    ("REABERTURA", "Reabertura"),
                    ("ARQUIVAMENTO_AUTOMATICO", "Arquivamento automático"),
                    ("COMENTARIO", "Comentário"),
                    ("ANEXO", "Anexo"),
                ],
                max_length=32,
                verbose_name="Tipo de evento",
            ),
        ),
    ]
