# Generated by Django 5.2.14 on 2026-06-11 21:21

import django.db.models.deletion
import reserva_espacos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prazo_maximo_agendamento_dias', models.PositiveIntegerField(default=15, verbose_name='Prazo máximo de agendamento (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('gestores_grupos', models.ManyToManyField(blank=True, related_name='categorias_reserva_gerenciadas', to='auth.group', verbose_name='Grupos gestores')),
                ('gestores_usuarios', models.ManyToManyField(blank=True, related_name='categorias_reserva_gerenciadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários gestores')),
            ],
            options={
                'verbose_name': 'Categoria de reserva',
                'verbose_name_plural': 'Categorias de reserva',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObjetoReservavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('localizacao', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('cor', models.CharField(default=reserva_espacos.models.random_calendar_color, max_length=7, verbose_name='Cor do calendário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='reservas_recursos.categoriareserva', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Objeto reservável',
                'verbose_name_plural': 'Objetos reserváveis',
                'ordering': ['categoria__nome', 'nome', 'id'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ReservaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de fim')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título da reserva')),
                ('responsavel', models.CharField(max_length=180, verbose_name='Responsável')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('serie_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Identificador da série')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_espacos_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas_recursos.objetoreservavel', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data', 'hora_inicio', 'id'],
            },
        ),
    ]
