# Generated by Django 5.2.14 on 2026-06-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_recursos', '0002_update_resource_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objetoreservavel',
            options={'ordering': ['nome', 'id'], 'verbose_name': 'Objeto reservável', 'verbose_name_plural': 'Objetos reserváveis'},
        ),
        migrations.AlterUniqueTogether(
            name='objetoreservavel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='objetoreservavel',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaReserva',
        ),
    ]
