# Generated by Django 5.2.14 on 2026-06-18 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def promover_reservas_legadas(apps, schema_editor):
    """Preserva as reservas já existentes como deferidas após a entrada do fluxo fiscal."""

    ReservaRecurso = apps.get_model("reservas_recursos", "ReservaRecurso")
    ReservaRecurso.objects.all().update(status="DEFERIDA")


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reservas_recursos', '0003_alter_objetoreservavel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoReservaEspacos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da reserva de espaços',
                'verbose_name_plural': 'Configurações da reserva de espaços',
            },
        ),
        migrations.CreateModel(
            name='ReservaRecursoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('CANCELAMENTO', 'Cancelamento'), ('DEFERIMENTO', 'Deferimento'), ('INDEFERIMENTO', 'Indeferimento')], max_length=20, verbose_name='Ação')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Detalhes complementares')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
            ],
            options={
                'verbose_name': 'Evento da reserva de espaço',
                'verbose_name_plural': 'Eventos da reserva de espaço',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='reservarecurso',
            name='fiscal_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_reserva_espacos', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal responsável'),
        ),
        migrations.AddField(
            model_name='reservarecurso',
            name='justificativa_indeferimento',
            field=models.TextField(blank=True, verbose_name='Justificativa do indeferimento'),
        ),
        migrations.AddField(
            model_name='reservarecurso',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='reservarecurso',
            index=models.Index(fields=['status', 'data'], name='reservas_re_status_77cffb_idx'),
        ),
        migrations.AddIndex(
            model_name='reservarecurso',
            index=models.Index(fields=['objeto', 'data', 'status'], name='reservas_re_objeto__2c1196_idx'),
        ),
        migrations.AddField(
            model_name='configuracaoreservaespacos',
            name='grupo_fiscais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_reserva_espacos', to='auth.group', verbose_name='Grupo de fiscais'),
        ),
        migrations.AddField(
            model_name='reservarecursoevento',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='reservas_recursos.reservarecurso', verbose_name='Reserva'),
        ),
        migrations.AddField(
            model_name='reservarecursoevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_reserva_espacos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.RunPython(promover_reservas_legadas, migrations.RunPython.noop),
    ]
