# Generated by Django 5.2.14 on 2026-06-17 23:22

import django.db.models.deletion
import reserva_garagem.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaGaragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('localizacao', models.CharField(blank=True, max_length=200, verbose_name='Localização')),
                ('cor', models.CharField(default=reserva_garagem.models.random_calendar_color, max_length=7, verbose_name='Cor do calendário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaga de garagem',
                'verbose_name_plural': 'Vagas de garagem',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoReservaGaragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo_fiscais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_reserva_garagem', to='auth.group', verbose_name='Grupo de fiscais')),
            ],
            options={
                'verbose_name': 'Configuração da reserva de garagem',
                'verbose_name_plural': 'Configurações da reserva de garagem',
            },
        ),
        migrations.CreateModel(
            name='ReservaGaragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Status')),
                ('data', models.DateField(verbose_name='Data')),
                ('responsavel', models.CharField(max_length=180, verbose_name='Responsável')),
                ('marca_veiculo', models.CharField(max_length=120, verbose_name='Marca do veículo')),
                ('modelo_veiculo', models.CharField(max_length=120, verbose_name='Modelo do veículo')),
                ('cor_veiculo', models.CharField(max_length=80, verbose_name='Cor do veículo')),
                ('placa_veiculo', models.CharField(max_length=10, verbose_name='Placa do veículo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('justificativa_indeferimento', models.TextField(blank=True, verbose_name='Justificativa do indeferimento')),
                ('serie_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Identificador da série')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fiscal_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_reserva_garagem', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal responsável')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_reserva_garagem', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva_garagem.vagagaragem', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Reserva de vaga',
                'verbose_name_plural': 'Reservas de vagas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservaGaragemEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('CANCELAMENTO', 'Cancelamento'), ('DEFERIMENTO', 'Deferimento'), ('INDEFERIMENTO', 'Indeferimento')], max_length=20, verbose_name='Ação')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Detalhes complementares')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='reserva_garagem.reservagaragem', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_reserva_garagem', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Evento da reserva de garagem',
                'verbose_name_plural': 'Eventos da reserva de garagem',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='reservagaragem',
            index=models.Index(fields=['status', 'data'], name='reserva_gar_status_7bc306_idx'),
        ),
        migrations.AddIndex(
            model_name='reservagaragem',
            index=models.Index(fields=['vaga', 'data', 'status'], name='reserva_gar_vaga_id_557417_idx'),
        ),
        migrations.AddIndex(
            model_name='reservagaragem',
            index=models.Index(fields=['placa_veiculo', 'data'], name='reserva_gar_placa_v_c09fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='reservagaragem',
            index=models.Index(fields=['solicitante', 'data'], name='reserva_gar_solicit_e7de10_idx'),
        ),
    ]
