# Generated by Django 5.2.14 on 2026-05-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_anexo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='anexo_pdf',
            field=models.FileField(blank=True, upload_to='noticias/anexos/', verbose_name='Anexo'),
        ),
    ]
