# Generated by Django 5.2.14 on 2026-06-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0003_seed_grupos_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='setornode',
            name='sistemico',
            field=models.BooleanField(default=False, help_text='Use para grupos destinados apenas a controle de acesso, sem exibição no organograma.', verbose_name='Grupo sistêmico'),
        ),
    ]
