# Generated by Django 5.2.14 on 2026-06-19 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Tarefa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de inserção')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_tecnicas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tarefa técnica',
                'verbose_name_plural': 'Tarefas técnicas',
                'ordering': ['concluido_em', '-criado_em', '-id'],
            },
        ),
    ]
