# Generated by OpenAI Codex em 19/06/2026.

from django.conf import settings
from django.db import migrations


def lock_todo_tecnico_acl_to_root(apps, schema_editor):
    """Restringe o recurso todo_tecnico a uma única regra vinculada ao usuário root."""

    Recurso = apps.get_model("acls", "Recurso")
    RegraAcesso = apps.get_model("acls", "RegraAcesso")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    recurso, _created = Recurso.objects.get_or_create(
        slug="todo_tecnico",
        defaults={
            "nome": "To-Do Técnico",
            "descricao": "Backlog técnico simplificado restrito ao usuário root.",
            "url_base": "/todo-tecnico/",
        },
    )
    if recurso.url_base != "/todo-tecnico/":
        recurso.url_base = "/todo-tecnico/"
        recurso.save(update_fields=["url_base"])

    root = User.objects.filter(username="root").first()

    # Qualquer regra anterior do recurso é removida para não restar acesso legado.
    RegraAcesso.objects.filter(recurso=recurso).delete()

    if not root:
        return

    regra = RegraAcesso.objects.create(
        recurso=recurso,
        nivel="CONTROLE_TOTAL",
    )
    regra.usuarios.add(root)


class Migration(migrations.Migration):

    dependencies = [
        ("acls", "0005_recurso_url_base"),
        ("todo_tecnico", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(lock_todo_tecnico_acl_to_root, migrations.RunPython.noop),
    ]
