# Generated by Django 5.2.14 on 2026-06-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_tecnico', '0002_lock_acl_to_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefatecnica',
            name='solucao',
            field=models.TextField(blank=True, verbose_name='Solução'),
        ),
        migrations.AlterField(
            model_name='tarefatecnica',
            name='titulo',
            field=models.TextField(blank=True, verbose_name='Título'),
        ),
    ]
