# Generated by Django 5.2.14 on 2026-06-19 19:10

from django.db import migrations, models


def copiar_titulo_para_descricao(apps, schema_editor):
    """Preserva o texto já existente nas tarefas antigas ao introduzir a descrição obrigatória."""

    TarefaTecnica = apps.get_model("todo_tecnico", "TarefaTecnica")
    for tarefa in TarefaTecnica.objects.all().iterator():
        tarefa.descricao = (tarefa.titulo or "").strip()
        tarefa.save(update_fields=["descricao"])


class Migration(migrations.Migration):

    dependencies = [
        ("todo_tecnico", "0003_tarefatecnica_solucao_alter_tarefatecnica_titulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefatecnica",
            name="descricao",
            field=models.TextField(default="", verbose_name="Descrição"),
            preserve_default=False,
        ),
        migrations.RunPython(copiar_titulo_para_descricao, migrations.RunPython.noop),
    ]
