# Generated by Django 5.2.14 on 2026-06-21 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_tecnico', '0004_tarefatecnica_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodexConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codex_path', models.CharField(default='/root/.local/bin/codex', max_length=255, verbose_name='Caminho do Codex CLI')),
                ('codex_home', models.CharField(default='/root/.codex', max_length=255, verbose_name='Diretório CODEX_HOME')),
                ('workspace_path', models.CharField(default='/root/aplicacoesspi', max_length=255, verbose_name='Diretório de trabalho')),
                ('modelo', models.CharField(default='gpt-5.4', max_length=120, verbose_name='Modelo padrão')),
                ('sandbox', models.CharField(default='workspace-write', max_length=60, verbose_name='Sandbox do Codex')),
                ('habilitar_busca_web', models.BooleanField(default=True, verbose_name='Habilitar busca web')),
                ('timeout_minutos', models.PositiveIntegerField(default=90, verbose_name='Tempo máximo por execução (minutos)')),
                ('limite_tokens_5h', models.PositiveIntegerField(default=250000, verbose_name='Limite de tokens em 5 horas')),
                ('limite_tokens_semanal', models.PositiveIntegerField(default=1500000, verbose_name='Limite semanal de tokens')),
                ('nome_servico', models.CharField(default='aplicacoesspi', max_length=120, verbose_name='Serviço para reinício')),
                ('instrucoes_fixas', models.TextField(default='Melhore o título da tarefa ou crie um título adequado quando ela estiver fraca ou vazia.\nPreencha a solução com um texto breve, mas elucidativo.\nTodo código gerado deve ser comentado de forma explicativa, sem excesso.\nEvite testes excessivos para economizar tokens, mas preserve a segurança da alteração.\nNão conclua a tarefa deixando a aplicação quebrada, inconsistente ou com erros.', verbose_name='Instruções fixas do Codex')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Codex',
                'verbose_name_plural': 'Configurações do Codex',
            },
        ),
        migrations.CreateModel(
            name='CodexExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('agendada', 'Agendada')], default='manual', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('na_fila', 'Na fila'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('erro', 'Erro'), ('cancelada', 'Cancelada')], default='na_fila', max_length=20, verbose_name='Status')),
                ('agendado_para', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('prompt_enviado', models.TextField(blank=True, verbose_name='Prompt enviado')),
                ('resposta_final', models.TextField(blank=True, verbose_name='Resposta final')),
                ('resumo_execucao', models.TextField(blank=True, verbose_name='Resumo da execução')),
                ('solucao_gerada', models.TextField(blank=True, verbose_name='Solução gerada')),
                ('titulo_gerado', models.TextField(blank=True, verbose_name='Título gerado')),
                ('log_resumido', models.TextField(blank=True, verbose_name='Log resumido')),
                ('log_completo', models.TextField(blank=True, verbose_name='Log completo')),
                ('saida_pos_execucao', models.TextField(blank=True, verbose_name='Saída pós-execução')),
                ('erro_detalhe', models.TextField(blank=True, verbose_name='Erro detalhado')),
                ('thread_id', models.CharField(blank=True, max_length=120, verbose_name='Thread do Codex')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de entrada')),
                ('cached_input_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de entrada em cache')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de saída')),
                ('reasoning_output_tokens', models.PositiveIntegerField(default=0, verbose_name='Tokens de raciocínio')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='Total de tokens')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_codex_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_codex', to='todo_tecnico.tarefatecnica', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Execução do Codex',
                'verbose_name_plural': 'Execuções do Codex',
                'ordering': ['status', 'agendado_para', '-criado_em', '-id'],
            },
        ),
    ]
