# Criado por José Eduardo Santana Martins em 04/06/2026
# Objetivo: Centralizar as configurações globais do Django, apps, autenticação,
# arquivos estáticos, mídia, banco de dados e templates do projeto.

"""
Django settings for aplicacoesspi project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Diretório base usado para montar caminhos de banco, templates, estáticos e mídia.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-key-change-me',
)

# Ambiente local/intranet: manter atenção ao desativar DEBUG em produção.
DEBUG = True

# Hosts conhecidos que podem acessar o portal na rede local e nos domínios institucionais.
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.23.1.245',
    '10.23.1.243',
    '100.94.53.27',
    'intranet',
    'intranet.spi.sp.gov.br',
    'portal',
    'portal.spi.sp.gov.br',
]

# O Nginx encerra o TLS e repassa a requisição ao Gunicorn em HTTP local.
# Este cabeçalho permite que o Django reconheça as requisições externas como HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Origens institucionais aceitas para validações CSRF em acessos HTTP/HTTPS do portal.
CSRF_TRUSTED_ORIGINS = [
    'https://portal.spi.sp.gov.br',
    'http://portal.spi.sp.gov.br',
    'https://intranet.spi.sp.gov.br',
    'http://intranet.spi.sp.gov.br',
    'http://10.23.1.245',
    'http://10.23.1.243',
    'http://100.94.53.27',
]


# Application definition

# Apps Django padrão, módulos do portal e apps de controle transversal do sistema.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assinatura_e_mail',
    'atalhos',
        'contratos',
    'licitacoes',
    'mensageria_assincrona',
    'navbar',
    'noticias',
    'reserva_carros',
    'reserva_garagem',
    'regulariza_sgi',
    'reserva_espacos',
    'setores',
    'tarefas',
    'usuarios',
    'acls',
    'organograma',
    'todo_tecnico',
]

# Middleware de segurança, arquivos estáticos, sessão, autenticação, mensagens e proteção de clickjacking.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aplicacoesspi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Templates globais ficam em BASE_DIR/templates; templates por app continuam habilitados.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            # Processadores globais disponibilizam request, usuário, mensagens e estado do perfil.
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mensageria_assincrona.context_processors.mensageria_global',
                'usuarios.context_processors.usuario_profile_state',
            ],
        },
    },
]

WSGI_APPLICATION = 'aplicacoesspi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'spi_db',
        'USER': 'spi_user',
        'PASSWORD': 'admin123',
        # Usa IPv4 explícito para evitar falhas intermitentes de resolução local
        # que estavam derrubando a conexão do Django com o PostgreSQL.
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'TEST': {
            'NAME': 'spi_db_test',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Arquivos enviados pelo usuário ficam separados dos estáticos coletados.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Fluxos de autenticação centralizam login, saída e redirecionamento inicial.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'root'
LOGOUT_REDIRECT_URL = 'login'
AUTHENTICATION_BACKENDS = [
    # LDAP institucional primeiro; backend nativo mantém acesso administrativo/local.
    'usuarios.backends.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
