# Generated by Django 5.2.14 on 2026-06-07 13:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contratodetalhamentoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciapagamento',
            name='gerada_automaticamente',
            field=models.BooleanField(default=True, verbose_name='Gerada automaticamente'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='valor_previsto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor previsto'),
        ),
    ]
