# Generated by Django 5.2.14 on 2026-06-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_competenciapagamento_gerada_automaticamente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciapagamento',
            name='anexo_atestado_realizacao',
            field=models.FileField(blank=True, upload_to='contratos/pagamentos/', verbose_name='Atestado de realização'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='anexo_despacho_dof',
            field=models.FileField(blank=True, upload_to='contratos/pagamentos/', verbose_name='Despacho DOF'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='anexo_nota_fiscal',
            field=models.FileField(blank=True, upload_to='contratos/pagamentos/', verbose_name='Anexo da nota fiscal'),
        ),
        migrations.AlterField(
            model_name='competenciapagamento',
            name='status',
            field=models.CharField(choices=[('BLOQUEADO', 'Bloqueado'), ('RASCUNHO', 'Rascunho'), ('EM_CONFERENCIA', 'Em conferência'), ('APTO_LIBERACAO', 'Apto para liberação'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20, verbose_name='Status'),
        ),
    ]
