# Generated by OpenAI Codex on 2026-06-08.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0004_competenciapagamento_anexo_atestado_realizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=80, unique=True, verbose_name='Número do contrato')),
                ('apelido', models.CharField(max_length=180, verbose_name='Apelido')),
                ('objeto', models.CharField(max_length=255, verbose_name='Objeto do contrato')),
                ('data_inicio_vigencia', models.DateField(verbose_name='Data de início da vigência')),
                ('prazo_inicial_meses', models.PositiveIntegerField(verbose_name='Prazo inicial (meses)')),
                ('vigencia_maxima_meses', models.PositiveIntegerField(verbose_name='Vigência máxima permitida (meses)')),
                ('situacao_forcada', models.CharField(blank=True, choices=[('', 'Automática'), ('VIGENTE', 'Vigente'), ('A_VENCER', 'À vencer'), ('ENCERRADO', 'Encerrado'), ('SUSPENSO', 'Suspenso')], default='', max_length=20, verbose_name='Situação forçada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_v2_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_v2_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa_contratada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_v2', to='contratos.empresacontratada', verbose_name='Empresa contratada')),
                ('fiscal_administrativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_v2_como_fiscal_administrativo', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal administrativo')),
                ('fiscal_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_v2_como_fiscal_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal técnico')),
                ('gestor_contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_v2_como_gestor', to=settings.AUTH_USER_MODEL, verbose_name='Gestor contrato')),
            ],
            options={
                'verbose_name': 'Contrato V2',
                'verbose_name_plural': 'Contratos V2',
                'ordering': ['numero_contrato', 'id'],
            },
        ),
    ]
