# Generated by Django 5.2.14 on 2026-06-08 18:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratov2',
            name='base_mensal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Base mensal'),
        ),
        migrations.AddField(
            model_name='contratov2',
            name='valor_global',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor global do contrato'),
        ),
        migrations.CreateModel(
            name='ContratoItemV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Item')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor unitário')),
                ('valor_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor subtotal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos_v2.contratov2')),
            ],
            options={
                'verbose_name': 'Item do contrato V2',
                'verbose_name_plural': 'Itens do contrato V2',
                'ordering': ['ordem', 'id'],
                'unique_together': {('contrato', 'ordem')},
            },
        ),
    ]
