# Generated by Django 5.2.14 on 2026-06-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0002_contratov2_base_mensal_contratov2_valor_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoitemv2',
            name='codigo_catmat_catser',
            field=models.CharField(blank=True, max_length=120, verbose_name='Código CATMAT/CATSER'),
        ),
        migrations.AddField(
            model_name='contratoitemv2',
            name='codigo_siafisico',
            field=models.CharField(blank=True, max_length=120, verbose_name='Código SIAFÍSICO'),
        ),
    ]
