# Generated by Django 5.2.14 on 2026-06-08 21:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0003_contratoitemv2_codigo_catmat_catser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCompetenciaItemV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('validado_em', models.DateTimeField(blank=True, null=True, verbose_name='Validado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item do checklist da competência',
                'verbose_name_plural': 'Itens do checklist da competência',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoQualidadeCompetenciaV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do formulário')),
                ('nota_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Nota final')),
                ('percentual_liberacao_sugerido', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Percentual sugerido')),
                ('valor_liberado_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor sugerido')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('manifestacao_gestor', models.TextField(blank=True, verbose_name='Manifestação do gestor')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('preenchido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_v2_preenchidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação da competência V2',
                'verbose_name_plural': 'Avaliações das competências V2',
                'ordering': ['competencia__periodo_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoCompetenciaItemRespostaV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nome', models.CharField(max_length=180, verbose_name='Grupo')),
                ('grupo_ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem do grupo')),
                ('grupo_peso_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Peso do grupo')),
                ('item_ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem do item')),
                ('item_descricao', models.TextField(verbose_name='Descrição do item')),
                ('item_peso_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Peso do item')),
                ('item_observacoes_padrao', models.TextField(blank=True, verbose_name='Observações padrão')),
                ('nota_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nota atribuída')),
                ('nota_legenda', models.CharField(blank=True, max_length=120, verbose_name='Legenda da nota')),
                ('justificativa_fiscal', models.TextField(blank=True, verbose_name='Justificativa do fiscal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos_v2.avaliacaoqualidadecompetenciav2')),
            ],
            options={
                'verbose_name': 'Resposta de item da avaliação',
                'verbose_name_plural': 'Respostas de itens da avaliação',
                'ordering': ['grupo_ordem', 'item_ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistCompetenciaAnexoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='contratos_v2/checklists/', verbose_name='Arquivo')),
                ('nome_exibicao', models.CharField(blank=True, max_length=220, verbose_name='Nome exibido')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexo', to='contratos_v2.checklistcompetenciaitemv2')),
            ],
            options={
                'verbose_name': 'Anexo do checklist da competência',
                'verbose_name_plural': 'Anexos do checklist da competência',
            },
        ),
        migrations.CreateModel(
            name='ChecklistModeloV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome da versão')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_modelos', to='contratos_v2.contratov2')),
            ],
            options={
                'verbose_name': 'Versão de checklist',
                'verbose_name_plural': 'Versões de checklist',
                'ordering': ['-ativo', '-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompetenciaPagamentoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Período inicial')),
                ('periodo_fim', models.DateField(verbose_name='Período final')),
                ('status', models.CharField(choices=[('BLOQUEADA', 'Bloqueada'), ('CHECKLIST_PENDENTE', 'Checklist pendente'), ('MEDICAO_PENDENTE', 'Medição pendente'), ('AVALIACAO_PENDENTE', 'Avaliação pendente'), ('PAGAMENTO_PENDENTE', 'Pagamento pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='BLOQUEADA', max_length=30, verbose_name='Status')),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor previsto')),
                ('valor_medido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor medido')),
                ('valor_liberado_sugerido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor liberado sugerido')),
                ('valor_liberado_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor liberado final')),
                ('checklist_modelo_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do checklist')),
                ('formulario_avaliacao_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot da avaliação')),
                ('checklist_concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Checklist concluído em')),
                ('medicao_concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Medição concluída em')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('nota_fiscal_fatura', models.FileField(blank=True, upload_to='contratos_v2/pagamentos/', verbose_name='Nota Fiscal/Fatura')),
                ('atestado_realizacao', models.FileField(blank=True, upload_to='contratos_v2/pagamentos/', verbose_name='Atestado de Realização')),
                ('despacho_dof', models.FileField(blank=True, upload_to='contratos_v2/pagamentos/', verbose_name='Despacho DOF')),
                ('justificativa_divergencia', models.TextField(blank=True, verbose_name='Justificativa de divergência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_v2_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='contratos_v2.contratov2')),
            ],
            options={
                'verbose_name': 'Competência V2',
                'verbose_name_plural': 'Competências V2',
                'ordering': ['periodo_inicio', 'id'],
                'unique_together': {('contrato', 'periodo_inicio', 'periodo_fim')},
            },
        ),
        migrations.AddField(
            model_name='checklistcompetenciaitemv2',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='contratos_v2.competenciapagamentov2'),
        ),
        migrations.AddField(
            model_name='avaliacaoqualidadecompetenciav2',
            name='competencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_qualidade', to='contratos_v2.competenciapagamentov2'),
        ),
        migrations.CreateModel(
            name='FormularioAvaliacaoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome da avaliação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('vigencia_inicio', models.DateField(verbose_name='Data de vigência')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Fim da vigência')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criterio_calculo', models.CharField(default='Média ponderada por grupo e item', max_length=180, verbose_name='Critério de cálculo da nota final')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_avaliacao', to='contratos_v2.contratov2')),
            ],
            options={
                'verbose_name': 'Formulário de avaliação',
                'verbose_name_plural': 'Formulários de avaliação',
                'ordering': ['-ativo', '-vigencia_inicio', '-id'],
            },
        ),
        migrations.AddField(
            model_name='avaliacaoqualidadecompetenciav2',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='contratos_v2.formularioavaliacaov2'),
        ),
        migrations.CreateModel(
            name='GrupoAvaliacaoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('peso_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Peso percentual')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='contratos_v2.formularioavaliacaov2')),
            ],
            options={
                'verbose_name': 'Grupo de avaliação',
                'verbose_name_plural': 'Grupos de avaliação',
                'ordering': ['ordem', 'id'],
                'unique_together': {('formulario', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistModeloItemV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos_v2.checklistmodelov2')),
            ],
            options={
                'verbose_name': 'Item da versão de checklist',
                'verbose_name_plural': 'Itens da versão de checklist',
                'ordering': ['ordem', 'id'],
                'unique_together': {('modelo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='FaixaLiberacaoAvaliacaoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nota mínima')),
                ('nota_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nota máxima')),
                ('percentual_liberacao', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Percentual de liberação')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_liberacao', to='contratos_v2.formularioavaliacaov2')),
            ],
            options={
                'verbose_name': 'Faixa de liberação',
                'verbose_name_plural': 'Faixas de liberação',
                'ordering': ['ordem', '-nota_minima', 'id'],
                'unique_together': {('formulario', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='EscalaNotaAvaliacaoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor numérico')),
                ('legenda', models.CharField(max_length=120, verbose_name='Legenda')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='contratos_v2.formularioavaliacaov2')),
            ],
            options={
                'verbose_name': 'Nota da escala',
                'verbose_name_plural': 'Notas da escala',
                'ordering': ['ordem', '-valor', 'id'],
                'unique_together': {('formulario', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ItemAvaliacaoV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de exibição')),
                ('descricao', models.TextField(verbose_name='Descrição do item')),
                ('peso_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Peso percentual dentro do grupo')),
                ('observacoes_padrao', models.TextField(blank=True, verbose_name='Observação padrão')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos_v2.grupoavaliacaov2')),
            ],
            options={
                'verbose_name': 'Item de avaliação',
                'verbose_name_plural': 'Itens de avaliação',
                'ordering': ['ordem', 'id'],
                'unique_together': {('grupo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='MedicaoItemCompetenciaV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Quantidade')),
                ('valor_unitario_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor unitário aplicado')),
                ('valor_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor subtotal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='contratos_v2.competenciapagamentov2')),
                ('item_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='contratos_v2.contratoitemv2')),
            ],
            options={
                'verbose_name': 'Medição da competência',
                'verbose_name_plural': 'Medições da competência',
                'ordering': ['item_contrato__ordem', 'id'],
                'unique_together': {('competencia', 'item_contrato')},
            },
        ),
    ]
