# Generated by Django 5.2.14 on 2026-06-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0004_checklistcompetenciaitemv2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formularioavaliacaov2',
            options={'ordering': ['-ativo', '-atualizado_em', '-id'], 'verbose_name': 'Formulário de avaliação', 'verbose_name_plural': 'Formulários de avaliação'},
        ),
        migrations.RemoveField(
            model_name='formularioavaliacaov2',
            name='vigencia_fim',
        ),
        migrations.RemoveField(
            model_name='formularioavaliacaov2',
            name='vigencia_inicio',
        ),
    ]
