# Generated by Django 5.2.14 on 2026-06-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0005_alter_formularioavaliacaov2_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioavaliacaov2',
            name='criterio_calculo',
        ),
    ]
