# Generated by Django 5.2.14 on 2026-06-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0006_remove_formularioavaliacaov2_criterio_calculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='grupo_peso_percentual',
        ),
        migrations.RemoveField(
            model_name='grupoavaliacaov2',
            name='peso_percentual',
        ),
    ]
