# Generated by Django 5.2.14 on 2026-06-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0007_remove_avaliacaocompetenciaitemrespostav2_grupo_peso_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciapagamentov2',
            name='aplicar_pro_rata',
            field=models.BooleanField(default=False, verbose_name='Aplicar pró-rata'),
        ),
    ]
