# Generated by Django 5.2.14 on 2026-06-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0008_competenciapagamentov2_aplicar_pro_rata'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='manifestacao_gestor_item',
            field=models.TextField(blank=True, verbose_name='Manifestação do gestor no item'),
        ),
    ]
