# Generated by Django 5.2.14 on 2026-06-09 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos_v2', '0009_avaliacaocompetenciaitemrespostav2_manifestacao_gestor_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='justificativa_fiscal_preenchida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Justificativa do fiscal preenchida em'),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='justificativa_fiscal_preenchida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_v2_justificativas_fiscais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='manifestacao_gestor_item_preenchida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manifestação do gestor preenchida em'),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='manifestacao_gestor_item_preenchida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_v2_manifestacoes_gestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='nota_fiscal_preenchida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nota do fiscal preenchida em'),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='nota_fiscal_preenchida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_v2_notas_fiscais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='nota_fiscal_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nota do fiscal'),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='nota_gestor_preenchida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nota do gestor preenchida em'),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='nota_gestor_preenchida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_v2_notas_gestor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaocompetenciaitemrespostav2',
            name='nota_gestor_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nota do gestor'),
        ),
    ]
