# Generated by Django 5.2.14 on 2026-05-27 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('host', models.CharField(max_length=255, verbose_name='Servidor')),
                ('port', models.PositiveIntegerField(default=389, verbose_name='Porta')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL')),
                ('base_dn', models.CharField(max_length=255, verbose_name='Base DN')),
                ('bind_dn', models.CharField(max_length=255, verbose_name='Usuario bind')),
                ('bind_password', models.CharField(max_length=255, verbose_name='Senha bind')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diretorio LDAP',
                'verbose_name_plural': 'Diretorios LDAP',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=220, verbose_name='Nome completo')),
                ('cargo', models.CharField(blank=True, max_length=180, verbose_name='Cargo')),
                ('setor', models.CharField(blank=True, max_length=180, verbose_name='Setor')),
                ('andar', models.CharField(blank=True, max_length=60, verbose_name='Andar')),
                ('bloco', models.CharField(blank=True, max_length=60, verbose_name='Bloco')),
                ('ultimo_recadastro_em', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo recadastro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfis de usuarios',
                'ordering': ['nome_completo', 'user__username'],
            },
        ),
    ]
