# Generated by Django 5.2.14 on 2026-05-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='ramal',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ramal'),
        ),
    ]
