# Generated by Django 5.2.14 on 2026-05-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarioperfil_ramal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='andar',
            field=models.CharField(blank=True, choices=[('Terreo', 'Terreo'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=60, verbose_name='Andar'),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='bloco',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=60, verbose_name='Bloco'),
        ),
    ]
