# Generated by Django 5.2.14 on 2026-05-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarioperfil_foto_alter_usuarioperfil_andar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioperfil',
            name='andar',
            field=models.CharField(blank=True, choices=[('Terreo', 'Térreo'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=60, verbose_name='Andar'),
        ),
    ]
