# Generated by Django 5.2.14 on 2026-06-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarioperfil_andar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
