# Generated by Django 5.2.14 on 2026-06-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarioperfil_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='celular',
            field=models.CharField(blank=True, max_length=40, verbose_name='Celular'),
        ),
    ]
