# Generated by Django 5.2.14 on 2026-06-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_usuarioperfil_celular"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarioperfil",
            name="superior_imediato",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="liderados_imediatos", to=settings.AUTH_USER_MODEL, verbose_name="Superior imediato"),
        ),
    ]
