# Generated by Django 5.2.14 on 2026-06-02 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_imobiliaria', models.CharField(max_length=120, unique=True, verbose_name='Inscrição imobiliária')),
                ('matricula', models.CharField(max_length=120, verbose_name='Matrícula')),
                ('processo_judicial', models.CharField(max_length=120, verbose_name='Processo judicial de desapropriação')),
                ('numero_sgi', models.CharField(max_length=120, verbose_name='Número SGI')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado')),
                ('municipio', models.CharField(max_length=120, verbose_name='Município')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=40, verbose_name='Número')),
                ('area', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Área (m²)')),
                ('possui_cadin', models.BooleanField(default=False, verbose_name='Possui notificação CADIN?')),
                ('exercicio_cadin', models.CharField(blank=True, max_length=15, verbose_name='Exercício da cobrança de IPTU')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CicloProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Ciclo')),
                ('tipo', models.CharField(choices=[('inicial', 'Inicial'), ('contrarrazao', 'Contrarrazão'), ('renovacao', 'Renovação')], default='inicial', max_length=20)),
                ('data_inicio', models.DateField(verbose_name='Data inicial')),
                ('numero_protocolo', models.CharField(blank=True, max_length=120, verbose_name='Número do protocolo')),
                ('data_protocolo', models.DateField(blank=True, null=True, verbose_name='Data do protocolo')),
                ('prazo_resposta_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de resposta')),
                ('prorrogacao_dias', models.PositiveIntegerField(default=0, verbose_name='Prorrogação (dias)')),
                ('data_prorrogacao', models.DateField(blank=True, null=True, verbose_name='Data da prorrogação')),
                ('data_manifestacao_prevista', models.DateField(blank=True, null=True, verbose_name='Manifestação prevista')),
                ('data_manifestacao', models.DateField(blank=True, null=True, verbose_name='Data da manifestação')),
                ('resultado', models.CharField(blank=True, choices=[('deferido', 'Deferido'), ('indeferido', 'Indeferido')], max_length=20, verbose_name='Resultado')),
                ('prazo_imunidade_anos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo da imunidade')),
                ('data_vencimento_imunidade', models.DateField(blank=True, null=True, verbose_name='Vencimento da imunidade')),
                ('data_renovacao_prevista', models.DateField(blank=True, null=True, verbose_name='Renovação prevista')),
                ('data_contrarrazao_limite', models.DateField(blank=True, null=True, verbose_name='Prazo para contrarrazão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='regulariza_sgi.imovel')),
            ],
            options={
                'verbose_name': 'Ciclo processual',
                'verbose_name_plural': 'Ciclos processuais',
                'ordering': ['-numero', '-id'],
                'unique_together': {('imovel', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ImovelAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(max_length=180, verbose_name='Nome exibido')),
                ('arquivo', models.FileField(upload_to='regulariza_sgi/anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='regulariza_sgi.imovel')),
            ],
            options={
                'verbose_name': 'Anexo do imóvel',
                'verbose_name_plural': 'Anexos do imóvel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImovelProcessoSEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sei', models.CharField(max_length=120, verbose_name='Número SEI')),
                ('link_sei', models.URLField(max_length=500, verbose_name='Link SEI')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_sei', to='regulariza_sgi.imovel')),
            ],
            options={
                'verbose_name': 'Processo SEI',
                'verbose_name_plural': 'Processos SEI',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MarcoProcessual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=120)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('data_real', models.DateField(blank=True, null=True, verbose_name='Data real')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='Data prevista')),
                ('prazo_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo em dias')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='regulariza_sgi.cicloprocessual')),
            ],
            options={
                'verbose_name': 'Marco processual',
                'verbose_name_plural': 'Marcos processuais',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
