# Generated by Django 5.2.14 on 2026-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulariza_sgi', '0003_imovel_notificacao_cadin_municipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Área (m²)'),
        ),
    ]
