# Generated by Django 5.2.14 on 2026-06-09 20:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_main_sei_fields(apps, schema_editor):
    """Leva o primeiro processo SEI legado para os novos campos principais do imóvel."""

    Imovel = apps.get_model('regulariza_sgi', 'Imovel')
    ImovelProcessoSEI = apps.get_model('regulariza_sgi', 'ImovelProcessoSEI')

    for imovel in Imovel.objects.all().iterator():
        processo = ImovelProcessoSEI.objects.filter(imovel_id=imovel.pk).order_by('id').first()
        if not processo:
            continue
        updates = {}
        if not imovel.sei:
            updates['sei'] = processo.numero_sei
        if not imovel.link_sei:
            updates['link_sei'] = processo.link_sei
        if updates:
            Imovel.objects.filter(pk=imovel.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('regulariza_sgi', '0005_marco_processual_usuario_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='divida_ativa',
            field=models.CharField(blank=True, max_length=180, verbose_name='Dívida ativa'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='dividas_ajuizadas',
            field=models.CharField(blank=True, max_length=180, verbose_name='Dívidas ajuizadas'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='dividas_nao_ajuizadas',
            field=models.CharField(blank=True, max_length=180, verbose_name='Dívidas não ajuizadas'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='encargos',
            field=models.CharField(blank=True, max_length=180, verbose_name='Encargos'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='exercicio_cobranca',
            field=models.CharField(blank=True, max_length=120, verbose_name='Exercício da cobrança'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='imissao_posse',
            field=models.DateField(blank=True, null=True, verbose_name='Imissão na posse'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='imunidade',
            field=models.BooleanField(default=False, verbose_name='Imunidade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='link_sei',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link SEI'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_divida',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nº da dívida'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sei',
            field=models.CharField(blank=True, max_length=120, verbose_name='SEI'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tempo_imunidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de imunidade (anos)'),
        ),
        migrations.CreateModel(
            name='ImovelObservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Observação')),
                ('usuario_responsavel', models.CharField(max_length=150, verbose_name='Usuário responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='regulariza_sgi.imovel')),
            ],
            options={
                'verbose_name': 'Observação do imóvel',
                'verbose_name_plural': 'Observações do imóvel',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImovelTimelineEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cadastro', 'Cadastro'), ('edicao', 'Edição'), ('observacao', 'Observação'), ('anexo', 'Anexo'), ('processo_sei', 'Processo SEI'), ('protocolo', 'Protocolo'), ('prorrogacao', 'Prorrogação'), ('manifestacao', 'Manifestação'), ('ciclo', 'Ciclo')], max_length=40, verbose_name='Tipo do evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('usuario_responsavel', models.CharField(blank=True, max_length=150, verbose_name='Usuário responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_eventos', to='regulariza_sgi.imovelanexo')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_eventos', to='regulariza_sgi.cicloprocessual')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_eventos', to='regulariza_sgi.imovel')),
                ('observacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_eventos', to='regulariza_sgi.imovelobservacao')),
                ('processo_sei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_eventos', to='regulariza_sgi.imovelprocessosei')),
            ],
            options={
                'verbose_name': 'Evento da timeline do imóvel',
                'verbose_name_plural': 'Eventos da timeline do imóvel',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.RunPython(migrate_main_sei_fields, migrations.RunPython.noop),
    ]
