# Generated by Django 5.2.14 on 2026-06-10 00:07

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def normalize_money_text(value):
    """Converte texto monetário legado para string decimal compatível com o banco."""

    if value in (None, ''):
        return None
    normalized = str(value).strip().replace('.', '').replace(',', '.')
    try:
        return str(Decimal(normalized).quantize(Decimal('0.01')))
    except (InvalidOperation, ValueError):
        return None


def migrate_legacy_money_fields(apps, schema_editor):
    """Normaliza os campos monetários que antes eram texto livre."""

    Imovel = apps.get_model('regulariza_sgi', 'Imovel')
    for imovel in Imovel.objects.all().iterator():
        updates = {}
        for field_name in ('dividas_nao_ajuizadas', 'dividas_ajuizadas', 'encargos'):
            converted = normalize_money_text(getattr(imovel, field_name))
            if converted != getattr(imovel, field_name):
                updates[field_name] = converted
        if updates:
            Imovel.objects.filter(pk=imovel.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('regulariza_sgi', '0006_imovel_divida_ativa_imovel_dividas_ajuizadas_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_money_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='imovel',
            name='dividas_ajuizadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Dívidas ajuizadas'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='dividas_nao_ajuizadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Dívidas não ajuizadas'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='encargos',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True, verbose_name='Encargos'),
        ),
    ]
