# Generated by Django 5.2.14 on 2026-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulariza_sgi', '0007_alter_imovel_dividas_ajuizadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='motivo_desapropriacao',
            field=models.TextField(blank=True, verbose_name='Motivo da desapropriação'),
        ),
    ]
