# Generated by Django 5.2.14 on 2026-06-12 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0003_seed_grupos_docs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=220, verbose_name='Assunto')),
                ('corpo', models.TextField(verbose_name='Corpo')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=20, verbose_name='Prioridade')),
                ('status_envio', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGENDADA', 'Agendada'), ('PUBLICADA', 'Publicada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='Status de envio')),
                ('origem_tipo', models.CharField(choices=[('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20, verbose_name='Origem pública')),
                ('origem_app', models.CharField(blank=True, max_length=120, verbose_name='App de origem')),
                ('origem_model', models.CharField(blank=True, max_length=120, verbose_name='Model de origem')),
                ('origem_pk', models.CharField(blank=True, max_length=120, verbose_name='PK de origem')),
                ('publicar_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicar em')),
                ('publicada_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicada em')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('payload_email', models.JSONField(blank=True, default=dict, verbose_name='Payload futuro de e-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSetorAlvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencia_setores', to='mensageria_assincrona.mensagem')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_audiencias_setor', to='setores.setornode')),
            ],
            options={
                'verbose_name': 'Setor alvo da mensagem',
                'verbose_name_plural': 'Setores alvo da mensagem',
                'ordering': ['mensagem_id', 'setor__group__name', 'id'],
                'unique_together': {('mensagem', 'setor')},
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='setores_alvo',
            field=models.ManyToManyField(blank=True, related_name='mensagens_audiencia_setor', through='mensageria_assincrona.MensagemSetorAlvo', to='setores.setornode', verbose_name='Setores selecionados'),
        ),
        migrations.CreateModel(
            name='MensagemUsuarioAlvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencia_usuarios', to='mensageria_assincrona.mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_audiencias_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário alvo da mensagem',
                'verbose_name_plural': 'Usuários alvo da mensagem',
                'ordering': ['mensagem_id', 'usuario__username', 'id'],
                'unique_together': {('mensagem', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='usuarios_alvo',
            field=models.ManyToManyField(blank=True, related_name='mensagens_audiencia_direta', through='mensageria_assincrona.MensagemUsuarioAlvo', to=settings.AUTH_USER_MODEL, verbose_name='Usuários selecionados'),
        ),
        migrations.CreateModel(
            name='MensagemDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_destinatario', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CIENTE', 'Ciente')], default='PENDENTE', max_length=20, verbose_name='Status do destinatário')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('visualizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Primeira visualização')),
                ('ciente_em', models.DateTimeField(blank=True, null=True, verbose_name='Ciência em')),
                ('assunto_snapshot', models.CharField(max_length=220, verbose_name='Assunto entregue')),
                ('corpo_snapshot', models.TextField(verbose_name='Corpo entregue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='mensageria_assincrona.mensagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destino da mensagem',
                'verbose_name_plural': 'Destinos da mensagem',
                'ordering': ['entregue_em', 'id'],
                'indexes': [models.Index(fields=['usuario', 'status_destinatario'], name='mensageria__usuario_09560c_idx'), models.Index(fields=['usuario', 'visualizada_em'], name='mensageria__usuario_94ae39_idx'), models.Index(fields=['usuario', 'ciente_em'], name='mensageria__usuario_bcf041_idx'), models.Index(fields=['usuario', 'entregue_em'], name='mensageria__usuario_f6e744_idx')],
                'unique_together': {('mensagem', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='MensagemEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('AGENDAMENTO', 'Agendamento'), ('PUBLICACAO', 'Publicação'), ('CANCELAMENTO', 'Cancelamento'), ('VISUALIZACAO', 'Visualização'), ('CIENCIA', 'Ciência')], max_length=20, verbose_name='Tipo de ação')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Informações complementares')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='mensageria_assincrona.mensagem')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_mensageria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento da mensagem',
                'verbose_name_plural': 'Eventos da mensagem',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tipo_acao', 'created_at'], name='mensageria__tipo_ac_da4354_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['status_envio', 'publicar_em'], name='mensageria__status__63ebc8_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['status_envio', 'publicada_em'], name='mensageria__status__846dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagem',
            index=models.Index(fields=['expira_em'], name='mensageria__expira__6f9094_idx'),
        ),
    ]
