# Generated by Django 5.2.14 on 2026-06-01 13:59

import atalhos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('imagem', models.ImageField(upload_to='atalhos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Imagem')),
                ('url', models.CharField(max_length=500, validators=[atalhos.models.validar_url_interna_ou_externa], verbose_name='URL')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atalho',
                'verbose_name_plural': 'Atalhos',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
