# Generated by Django 5.2.14 on 2026-06-12 16:36

import django.db.models.deletion
import reserva_carros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=120, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=120, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('cor', models.CharField(default=reserva_carros.models.random_calendar_color, max_length=7, verbose_name='Cor do calendário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['marca', 'modelo', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=220, verbose_name='Nome completo')),
                ('contato', models.CharField(blank=True, max_length=120, verbose_name='Contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome_completo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoReservaCarros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo_fiscais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_reserva_carros', to='auth.group', verbose_name='Grupo de fiscais')),
            ],
            options={
                'verbose_name': 'Configuração da reserva de carros',
                'verbose_name_plural': 'Configurações da reserva de carros',
            },
        ),
        migrations.CreateModel(
            name='ReservaCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO_APROVACAO', max_length=30, verbose_name='Status')),
                ('saida_planejada_em', models.DateTimeField(verbose_name='Saída planejada')),
                ('retorno_planejado_em', models.DateTimeField(verbose_name='Retorno planejado')),
                ('local_saida', models.CharField(default='Secretaria de Parcerias em Investimentos', max_length=220, verbose_name='Local de saída')),
                ('destino_endereco', models.CharField(max_length=300, verbose_name='Destino')),
                ('modo_destino', models.CharField(choices=[('AGUARDAR_NO_LOCAL', 'Aguardar no local'), ('SOMENTE_DESEMBARQUE', 'Somente desembarque')], max_length=30, verbose_name='Permanência no destino')),
                ('motivo_viagem', models.TextField(verbose_name='Motivo da viagem')),
                ('observacoes_solicitante', models.TextField(blank=True, verbose_name='Observações do solicitante')),
                ('justificativa_indeferimento', models.TextField(blank=True, verbose_name='Justificativa do indeferimento')),
                ('deslocamento_ida_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deslocamento de ida (min)')),
                ('deslocamento_retorno_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deslocamento de retorno (min)')),
                ('inicio_bloqueio_em', models.DateTimeField(blank=True, null=True, verbose_name='Início do bloqueio')),
                ('fim_bloqueio_em', models.DateTimeField(blank=True, null=True, verbose_name='Fim do bloqueio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('carro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reserva_carros.carro', verbose_name='Carro')),
                ('fiscal_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_reserva_carro', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal responsável')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reserva_carros.motorista', verbose_name='Motorista')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_reserva_carro', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Reserva de carro',
                'verbose_name_plural': 'Reservas de carros',
                'ordering': ['-saida_planejada_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCarroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('CANCELAMENTO', 'Cancelamento'), ('DEFERIMENTO', 'Deferimento'), ('INDEFERIMENTO', 'Indeferimento')], max_length=20, verbose_name='Ação')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Detalhes complementares')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='reserva_carros.reservacarro', verbose_name='Reserva')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_reserva_carro', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
            ],
            options={
                'verbose_name': 'Evento da reserva de carro',
                'verbose_name_plural': 'Eventos da reserva de carro',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCarroPassageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros_vinculos', to='reserva_carros.reservacarro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_como_passageiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passageiro da reserva',
                'verbose_name_plural': 'Passageiros da reserva',
                'ordering': ['usuario__username', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reservacarro',
            index=models.Index(fields=['status', 'saida_planejada_em'], name='reserva_car_status_0c3da6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservacarro',
            index=models.Index(fields=['carro', 'inicio_bloqueio_em', 'fim_bloqueio_em'], name='reserva_car_carro_i_dcd9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='reservacarro',
            index=models.Index(fields=['motorista', 'inicio_bloqueio_em', 'fim_bloqueio_em'], name='reserva_car_motoris_6410fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservacarropassageiro',
            unique_together={('reserva', 'usuario')},
        ),
    ]
