# Generated by Django 5.2.14 on 2026-05-18 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtpTic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('numero_processo', models.CharField(max_length=120, verbose_name='Numero do processo')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link do processo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONCLUIDO', 'Concluido')], default='RASCUNHO', max_length=20)),
                ('secao_atual', models.PositiveIntegerField(default=1)),
                ('descricao_necessidade', models.TextField(blank=True)),
                ('area_requisitante', models.CharField(blank=True, max_length=180)),
                ('responsavel_area', models.CharField(blank=True, max_length=180)),
                ('necessidades_negocio', models.TextField(blank=True)),
                ('necessidades_tecnologicas', models.TextField(blank=True)),
                ('demais_requisitos', models.TextField(blank=True)),
                ('estimativa_demanda', models.TextField(blank=True)),
                ('levantamento_solucoes', models.TextField(blank=True)),
                ('analise_comparativa_solucoes', models.TextField(blank=True)),
                ('solucoes_inviaveis', models.TextField(blank=True)),
                ('analise_comparativa_custos_tco', models.TextField(blank=True)),
                ('descricao_solucao_tic', models.TextField(blank=True)),
                ('estimativa_custo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimativa_custo_texto', models.TextField(blank=True)),
                ('justificativa_tecnica', models.TextField(blank=True)),
                ('justificativa_economica', models.TextField(blank=True)),
                ('beneficios_contratacao', models.TextField(blank=True)),
                ('providencias_adotadas', models.TextField(blank=True)),
                ('declaracao_viabilidade', models.TextField(default='Esta equipe de planejamento declara viavel esta contratacao.')),
                ('justificativa_viabilidade', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TermoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('numero_processo', models.CharField(max_length=120, verbose_name='Numero do processo')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Link do processo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUMERICO', 'Item/Subitem'), ('INCISO', 'Inciso'), ('ALINEA', 'Alinea')], default='NUMERICO', max_length=12)),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='licitacoes.itemtr')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='licitacoes.sessaotr')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sessaotr',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='licitacoes.termoreferencia'),
        ),
    ]
