# Generated by Django 5.2.14 on 2026-05-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaItemLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('catmat_catser', models.CharField(blank=True, max_length=120, verbose_name='CATMAT/CATSER')),
                ('siafisico', models.CharField(blank=True, max_length=120, verbose_name='Siafisico')),
                ('unidade_fornecimento', models.CharField(blank=True, max_length=120, verbose_name='Unidade de Fornecimento')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_linhas', to='licitacoes.itemtr')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
