# Generated by Django 5.2.14 on 2026-05-19 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0002_tabelaitemlinha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('numero_processo', models.CharField(max_length=120, verbose_name='Numero do processo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONCLUIDO', 'Concluido')], default='RASCUNHO', max_length=20)),
                ('secao_atual', models.PositiveIntegerField(default=1)),
                ('informacoes_preliminares', models.TextField(blank=True)),
                ('descricao_objeto', models.TextField(blank=True)),
                ('justificativa_necessidade', models.TextField(blank=True)),
                ('estimativa_quantidade_valores', models.TextField(blank=True)),
                ('vinculacao_outro_dfd', models.TextField(blank=True)),
                ('responsaveis', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DfdItemTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('item', models.CharField(blank=True, max_length=40)),
                ('equipamento', models.CharField(max_length=180)),
                ('catmat', models.CharField(blank=True, max_length=120, verbose_name='CATMAT')),
                ('siafisico', models.CharField(blank=True, max_length=120, verbose_name='SIAFISICO')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dfd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_tabela', to='licitacoes.dfd')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
