# Generated by Django 5.2.14 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0004_altera_tabela_dfd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfditemtabela',
            name='siafisico',
            field=models.CharField(blank=True, max_length=120, verbose_name='SIAFISICO'),
        ),
    ]
