# Generated by Django 5.2.14 on 2026-05-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0005_dfditemtabela_siafisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='objeto_nao_luxo',
            field=models.TextField(blank=True, default='1.2. O objeto desta contratação não se enquadra como sendo de bem de luxo, conforme Decreto nº 67.985, de 27 de setembro de 2023.', verbose_name='Item 1.2'),
        ),
    ]
