# Generated by Django 5.2.14 on 2026-05-22 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0006_dfd_objeto_nao_luxo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etptic',
            name='usa_editor_dinamico',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessaoEtpTic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='licitacoes.etptic')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemEtpTic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='licitacoes.itemetptic')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='licitacoes.sessaoetptic')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
