# Generated by Django 5.2.14 on 2026-05-25 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0009_itemetptic_alinea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='etptic',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etps_tic_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termoreferencia',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_referencia_atualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
