# Generated by Django 5.2.14 on 2026-05-26 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0010_etptic_atualizado_por_termoreferencia_atualizado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=220, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=60, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contato', models.CharField(max_length=180, verbose_name='Contato')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail do contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['razao_social', 'cnpj'],
            },
        ),
        migrations.CreateModel(
            name='PesquisaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AQUISICAO', 'Aquisição'), ('SERVICO', 'Serviço')], max_length=20, verbose_name='Tipo')),
                ('vigencia_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Vigência em meses')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('termo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa_preco', to='licitacoes.termoreferencia')),
            ],
            options={
                'ordering': ['-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PesquisaPrecoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateField(blank=True, null=True, verbose_name='Data da resposta')),
                ('validade_orcamento_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Validade do orçamento em dias')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_preco', to='licitacoes.fornecedor')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_pesquisa', to='licitacoes.pesquisapreco')),
            ],
            options={
                'ordering': ['fornecedor__razao_social', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PesquisaPrecoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contato', models.DateField(verbose_name='Data do contato')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pesquisa_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='licitacoes.pesquisaprecofornecedor')),
            ],
            options={
                'ordering': ['-data_contato', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PesquisaPrecoItemValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Preço unitário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_pesquisa_preco', to='licitacoes.tabelaitemlinha')),
                ('pesquisa_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='licitacoes.pesquisaprecofornecedor')),
            ],
            options={
                'ordering': ['item__ordem', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='pesquisaprecofornecedor',
            constraint=models.UniqueConstraint(fields=('pesquisa', 'fornecedor'), name='uniq_fornecedor_por_pesquisa_preco'),
        ),
        migrations.AddConstraint(
            model_name='pesquisaprecoitemvalor',
            constraint=models.UniqueConstraint(fields=('pesquisa_fornecedor', 'item'), name='uniq_preco_item_por_fornecedor'),
        ),
    ]
