# Generated by Django 5.2.14 on 2026-05-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0011_fornecedor_pesquisapreco_pesquisaprecofornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisapreco',
            name='pesquisador_cargo',
            field=models.CharField(default='', max_length=180, verbose_name='Cargo do pesquisador'),
        ),
        migrations.AddField(
            model_name='pesquisapreco',
            name='pesquisador_email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-mail do pesquisador'),
        ),
        migrations.AddField(
            model_name='pesquisapreco',
            name='pesquisador_nome',
            field=models.CharField(default='', max_length=180, verbose_name='Nome do pesquisador'),
        ),
        migrations.AlterField(
            model_name='pesquisaprecofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas_preco', to='licitacoes.fornecedor'),
        ),
    ]
