# Generated by Django 5.2.14 on 2026-05-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0012_pesquisapreco_pesquisador_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
    ]
