# Generated by Django 5.2.14 on 2026-05-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0013_remove_fornecedor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisaprecofornecedor',
            name='documento_fornecedor',
            field=models.FileField(blank=True, upload_to='licitacoes/pesquisa_preco/orcamentos/', verbose_name='Documento do fornecedor'),
        ),
    ]
