# Generated by Django 5.2.14 on 2026-05-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0014_pesquisaprecofornecedor_documento_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='email_contato',
            field=models.CharField(max_length=500, verbose_name='E-mail do contato'),
        ),
    ]
