# Generated by Django 5.2.14 on 2026-05-27 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0015_alter_fornecedor_email_contato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dfds_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etptic',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etps_tic_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termoreferencia',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos_referencia_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
