# Generated by Django 5.2.14 on 2026-05-27 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0016_dfd_criado_por_etptic_criado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dfd',
            name='compartilhado_com',
            field=models.ManyToManyField(blank=True, related_name='dfds_compartilhados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etptic',
            name='compartilhado_com',
            field=models.ManyToManyField(blank=True, related_name='etps_tic_compartilhados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termoreferencia',
            name='compartilhado_com',
            field=models.ManyToManyField(blank=True, related_name='termos_referencia_compartilhados', to=settings.AUTH_USER_MODEL),
        ),
    ]
