# Generated by Django 5.2.14 on 2026-05-27 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitacoes', '0017_dfd_compartilhado_com_etptic_compartilhado_com_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesquisaPrecoFornecedorNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Nota')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_pesquisa_preco', to=settings.AUTH_USER_MODEL)),
                ('pesquisa_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='licitacoes.pesquisaprecofornecedor')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
