# Generated by Django 5.2.14 on 2026-06-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Recurso')),
                ('slug', models.SlugField(help_text="Usado no código para identificar este recurso. Ex: 'licitacoes'", max_length=100, unique=True, verbose_name='Slug identificador')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Recurso Protegido',
                'verbose_name_plural': 'Recursos Protegidos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIBERAR', 'Liberar Acesso'), ('BLOQUEAR', 'Bloquear Acesso')], default='LIBERAR', max_length=10, verbose_name='Ação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(blank=True, help_text='Deixe em branco se a regra for individual para um usuário.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_acesso', to='auth.group', verbose_name='Grupo/Setor')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='acls.recurso')),
                ('usuario', models.ForeignKey(blank=True, help_text='Deixe em branco se a regra for aplicada para um grupo/setor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (Individual)')),
            ],
            options={
                'verbose_name': 'Regra de Acesso',
                'verbose_name_plural': 'Regras de Acesso',
                'ordering': ['-id'],
            },
        ),
    ]
