# Generated by Django 5.2.14 on 2026-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'ordering': ['nome'], 'verbose_name': 'App/Recurso Protegido', 'verbose_name_plural': 'Apps/Recursos Protegidos'},
        ),
        migrations.RemoveField(
            model_name='regraacesso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='regraacesso',
            name='nivel',
            field=models.CharField(choices=[('LEITURA', 'Leitura (Vê tudo)'), ('MODIFICACAO', 'Modificação (Cria, vê e edita o próprio)'), ('CONTROLE_TOTAL', 'Controle Total (Cria, vê e edita todos)')], default='LEITURA', max_length=20, verbose_name='Nível de Permissão'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do App/Recurso'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='slug',
            field=models.SlugField(help_text="Nome da pasta do app (ex: 'licitacoes')", max_length=100, unique=True, verbose_name='Slug identificador'),
        ),
    ]
