# Generated by Django 5.2.14 on 2026-06-04 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0002_alter_recurso_options_remove_regraacesso_tipo_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraacesso',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Selecione o grupo/setor para aplicar a regra.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_acesso', to='auth.group', verbose_name='Grupo/Setor'),
        ),
        migrations.AlterField(
            model_name='regraacesso',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Selecione o usuário para aplicar a regra.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_acesso', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
