# Generated by Django 5.2.14 on 2026-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acls', '0004_regraacesso_multiplos_alvos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='url_base',
            field=models.CharField(blank=True, help_text='Opcional. Quando preenchida, substitui a URL derivada do slug.', max_length=160, verbose_name='URL base'),
        ),
    ]
