# Generated by Django 5.2.14 on 2026-06-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrazoMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_limite', models.DateField(verbose_name='Data limite')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='contratos/prazos/', verbose_name='Anexo')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Prazo de monitoramento',
                'verbose_name_plural': 'Prazos de monitoramento',
                'ordering': ['concluido', 'data_limite', 'criado_em'],
            },
        ),
    ]
