# Generated by Django 5.2.14 on 2026-06-07 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoDetalhamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhamento_itens', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Item do detalhamento do objeto',
                'verbose_name_plural': 'Itens do detalhamento do objeto',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
