# Generated by Django 5.2.14 on 2026-06-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_prazomonitoramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciapagamento',
            name='status',
            field=models.CharField(choices=[('BLOQUEADA', 'Bloqueada'), ('CHECKLIST_PENDENTE', 'Checklist pendente'), ('MEDICAO_PENDENTE', 'Medição pendente'), ('AVALIACAO_PENDENTE', 'Avaliação pendente'), ('PAGAMENTO_PENDENTE', 'Pagamento pendente'), ('PAGAMENTO_REGISTRADO', 'Pagamento registrado'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='BLOQUEADA', max_length=30, verbose_name='Status'),
        ),
    ]
