# Generated by Django 5.2.14 on 2026-06-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_competenciapagamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prazomonitoramento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
    ]
