# Generated by Django 5.2.14 on 2026-06-15 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_prazomonitoramento_data_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_fiscal_administrativo', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal administrativo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_fiscal_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal técnico'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='gestor_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_gestor', to=settings.AUTH_USER_MODEL, verbose_name='Gestor contrato'),
        ),
    ]
