# Generated by Django 5.2.14 on 2026-06-15 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_alter_contrato_fiscal_administrativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoImportanteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=220, verbose_name='Nome')),
                ('arquivo', models.FileField(upload_to='contratos/documentos_importantes/', verbose_name='Anexo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_importantes_contrato_atualizados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_importantes', to='contratos.contrato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_importantes_contrato_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento importante do contrato',
                'verbose_name_plural': 'Documentos importantes do contrato',
                'ordering': ['id'],
            },
        ),
    ]
