# Generated by Django 5.2.14 on 2026-06-15 22:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_documentoimportantecontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciapagamento',
            name='retencao_cofins',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção COFINS'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='retencao_inss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção INSS'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='retencao_ir',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção IR'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='retencao_iss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção ISS'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='retencao_pis_pasep',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção PIS/PASEP'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='valor_nota_fiscal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor da nota fiscal'),
        ),
    ]
