# Generated by Django 5.2.14 on 2026-06-16 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_competenciapagamento_retencao_cofins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciapagamento',
            name='coordenadora_em_exercicio',
            field=models.BooleanField(default=False, verbose_name='Coordenadora em exercício'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='coordenadora_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_v2_como_coordenadora_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Coordenadora'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='diretora_em_exercicio',
            field=models.BooleanField(default=False, verbose_name='Diretora em exercício'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='diretora_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_v2_como_diretora_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Diretora'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='gestor_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_v2_como_gestor_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Gestor do contrato'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='gestor_pagamento_em_exercicio',
            field=models.BooleanField(default=False, verbose_name='Gestor do contrato em exercício'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='subsecretario_em_exercicio',
            field=models.BooleanField(default=False, verbose_name='Subsecretário em exercício'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='subsecretario_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencias_v2_como_subsecretario_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Subsecretário'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fiscal_administrativo_suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_fiscal_administrativo_suplente', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal administrativo suplente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fiscal_tecnico_suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_fiscal_tecnico_suplente', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal técnico suplente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='gestor_contrato_suplente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_como_gestor_suplente', to=settings.AUTH_USER_MODEL, verbose_name='Gestor suplente'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='processo_sei_execucao_numero',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Processo SEI (Execução) - número'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='processo_sei_execucao_url',
            field=models.URLField(blank=True, default='', verbose_name='Processo SEI (Execução) - link'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='processo_sei_gestao_numero',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Processo SEI (Gestão) - número'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='processo_sei_gestao_url',
            field=models.URLField(blank=True, default='', verbose_name='Processo SEI (Gestão) - link'),
        ),
    ]
