# Generated by Django 5.2.14 on 2026-06-16 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_competenciapagamento_coordenadora_em_exercicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportacaoDocumentosCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('etapa_atual', models.CharField(blank=True, max_length=120, verbose_name='Etapa atual')),
                ('percentual', models.PositiveSmallIntegerField(default=0, verbose_name='Percentual')),
                ('mensagem', models.CharField(blank=True, max_length=255, verbose_name='Mensagem')),
                ('arquivo_pdf', models.FileField(blank=True, upload_to='contratos/downloads/', verbose_name='Arquivo PDF consolidado')),
                ('erro_detalhe', models.TextField(blank=True, verbose_name='Detalhes do erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes_documentos', to='contratos.competenciapagamento')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exportacoes_documentos_competencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exportação de documentos da competência',
                'verbose_name_plural': 'Exportações de documentos das competências',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
