# Generated by Django 5.2.14 on 2026-06-16 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_exportacaodocumentoscompetencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPadraoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome da versão')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_padrao_globais_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_padrao_globais_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checklist padrão global',
                'verbose_name_plural': 'Checklists padrão globais',
                'ordering': ['-ativo', '-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistPadraoGlobalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('checklist_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.checklistpadraoglobal')),
            ],
            options={
                'verbose_name': 'Item do checklist padrão global',
                'verbose_name_plural': 'Itens do checklist padrão global',
                'ordering': ['ordem', 'id'],
                'unique_together': {('checklist_padrao', 'ordem')},
            },
        ),
    ]
