# Generated by Django 5.2.14 on 2026-06-17 18:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_competencia_nota_adicional_nao_consta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciapagamento',
            name='retencao_cofins_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção COFINS da nota adicional'),
        ),
        migrations.AlterField(
            model_name='competenciapagamento',
            name='retencao_inss_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção INSS da nota adicional'),
        ),
        migrations.AlterField(
            model_name='competenciapagamento',
            name='retencao_ir_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção IR da nota adicional'),
        ),
        migrations.AlterField(
            model_name='competenciapagamento',
            name='retencao_iss_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção ISS da nota adicional'),
        ),
        migrations.AlterField(
            model_name='competenciapagamento',
            name='retencao_pis_pasep_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Retenção PIS/PASEP da nota adicional'),
        ),
        migrations.AlterField(
            model_name='competenciapagamento',
            name='valor_liquido_nota_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor líquido da nota adicional'),
        ),
        migrations.AlterField(
            model_name='competenciapagamento',
            name='valor_nota_adicional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor da nota fiscal adicional'),
        ),
        migrations.CreateModel(
            name='FormularioAvaliacaoPadraoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome da avaliação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_avaliacao_padrao_globais_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_avaliacao_padrao_globais_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulário de avaliação padrão global',
                'verbose_name_plural': 'Formulários de avaliação padrão globais',
                'ordering': ['-ativo', '-atualizado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoAvaliacaoPadraoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('formulario_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='contratos.formularioavaliacaopadraoglobal')),
            ],
            options={
                'verbose_name': 'Grupo de avaliação padrão global',
                'verbose_name_plural': 'Grupos de avaliação padrão global',
                'ordering': ['ordem', 'id'],
                'unique_together': {('formulario_padrao', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='FaixaLiberacaoAvaliacaoPadraoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('nota_minima', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Nota mínima')),
                ('nota_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nota máxima')),
                ('percentual_liberacao', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Percentual de liberação')),
                ('formulario_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_liberacao', to='contratos.formularioavaliacaopadraoglobal')),
            ],
            options={
                'verbose_name': 'Faixa de liberação padrão global',
                'verbose_name_plural': 'Faixas de liberação padrão global',
                'ordering': ['ordem', '-nota_minima', 'id'],
                'unique_together': {('formulario_padrao', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='EscalaNotaAvaliacaoPadraoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor numérico')),
                ('legenda', models.CharField(max_length=120, verbose_name='Legenda')),
                ('formulario_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='contratos.formularioavaliacaopadraoglobal')),
            ],
            options={
                'verbose_name': 'Nota da escala padrão global',
                'verbose_name_plural': 'Notas da escala padrão global',
                'ordering': ['ordem', '-valor', 'id'],
                'unique_together': {('formulario_padrao', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ItemAvaliacaoPadraoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de exibição')),
                ('descricao', models.TextField(verbose_name='Descrição do item')),
                ('peso_percentual', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, verbose_name='Peso percentual dentro do grupo')),
                ('observacoes_padrao', models.TextField(blank=True, verbose_name='Observação padrão')),
                ('grupo_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.grupoavaliacaopadraoglobal')),
            ],
            options={
                'verbose_name': 'Item de avaliação padrão global',
                'verbose_name_plural': 'Itens de avaliação padrão global',
                'ordering': ['ordem', 'id'],
                'unique_together': {('grupo_padrao', 'ordem')},
            },
        ),
    ]
