# Generated by Django 5.2.14 on 2026-06-20 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_alter_competenciapagamento_retencao_cofins_adicional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaAuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('COMPETENCIA_CRIADA', 'Competência criada'), ('CHECKLIST_ATUALIZADO', 'Checklist atualizado'), ('MEDICAO_ATUALIZADA', 'Medição atualizada'), ('AVALIACAO_ATUALIZADA', 'Avaliação atualizada'), ('OB_EXECUTADA', 'Ordem bancária executada'), ('PAGAMENTO_EXECUTADO', 'Pagamento executado'), ('CANCELAMENTO_REGISTRADO', 'Cancelamento registrado')], max_length=50, verbose_name='Tipo do evento')),
                ('resumo', models.CharField(max_length=255, verbose_name='Resumo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_eventos', to='contratos.competenciapagamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencia_auditoria_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria da competência',
                'verbose_name_plural': 'Eventos de auditoria da competência',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['competencia', '-created_at', '-id'], name='comp_audit_cmp_dt_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContratoAuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CONTRATO_CRIADO', 'Contrato criado'), ('CONTRATO_ATUALIZADO', 'Contrato atualizado'), ('ITEM_CRIADO', 'Item criado'), ('ITEM_ATUALIZADO', 'Item atualizado'), ('ITEM_EXCLUIDO', 'Item excluído'), ('DOCUMENTO_CRIADO', 'Documento criado'), ('DOCUMENTO_ATUALIZADO', 'Documento atualizado'), ('DOCUMENTO_EXCLUIDO', 'Documento excluído'), ('CHECKLIST_CRIADO', 'Checklist criado'), ('CHECKLIST_ATUALIZADO', 'Checklist atualizado'), ('CHECKLIST_EXCLUIDO', 'Checklist excluído'), ('CHECKLIST_ITEM_CRIADO', 'Item de checklist criado'), ('CHECKLIST_ITEM_ATUALIZADO', 'Item de checklist atualizado'), ('CHECKLIST_ITEM_EXCLUIDO', 'Item de checklist excluído'), ('CHECKLIST_PADRAO_CARREGADO', 'Checklist padrão carregado'), ('FORMULARIO_CRIADO', 'Formulário criado'), ('FORMULARIO_ATUALIZADO', 'Formulário atualizado'), ('FORMULARIO_EXCLUIDO', 'Formulário excluído'), ('ESCALA_CRIADA', 'Escala criada'), ('ESCALA_ATUALIZADA', 'Escala atualizada'), ('ESCALA_EXCLUIDA', 'Escala excluída'), ('FAIXA_CRIADA', 'Faixa criada'), ('FAIXA_ATUALIZADA', 'Faixa atualizada'), ('FAIXA_EXCLUIDA', 'Faixa excluída'), ('GRUPO_CRIADO', 'Grupo criado'), ('GRUPO_ATUALIZADO', 'Grupo atualizado'), ('GRUPO_EXCLUIDO', 'Grupo excluído'), ('ITEM_AVALIACAO_CRIADO', 'Item de avaliação criado'), ('ITEM_AVALIACAO_ATUALIZADO', 'Item de avaliação atualizado'), ('ITEM_AVALIACAO_EXCLUIDO', 'Item de avaliação excluído'), ('FORMULARIO_PADRAO_CARREGADO', 'Formulário padrão carregado'), ('COMPETENCIAS_GERADAS', 'Competências geradas'), ('PRAZO_CRIADO', 'Prazo criado'), ('PRAZO_ATUALIZADO', 'Prazo atualizado'), ('PRAZO_CONCLUIDO', 'Prazo concluído'), ('PRAZO_EXCLUIDO', 'Prazo excluído')], max_length=50, verbose_name='Tipo do evento')),
                ('resumo', models.CharField(max_length=255, verbose_name='Resumo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria_eventos', to='contratos.contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_auditoria_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria do contrato',
                'verbose_name_plural': 'Eventos de auditoria do contrato',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['contrato', '-created_at', '-id'], name='contr_audit_ctr_dt_idx')],
            },
        ),
    ]
