# Generated by Django 5.2.14 on 2026-06-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_auditoria_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciaauditoriaevento',
            name='tipo_evento',
            field=models.CharField(choices=[('COMPETENCIA_CRIADA', 'Competência criada'), ('CHECKLIST_ATUALIZADO', 'Checklist atualizado'), ('MEDICAO_ATUALIZADA', 'Medição atualizada'), ('AVALIACAO_ATUALIZADA', 'Avaliação atualizada'), ('RESET_EXECUTADO', 'Reset executado'), ('OB_EXECUTADA', 'Ordem bancária executada'), ('PAGAMENTO_EXECUTADO', 'Pagamento executado'), ('CANCELAMENTO_REGISTRADO', 'Cancelamento registrado')], max_length=50, verbose_name='Tipo do evento'),
        ),
    ]
