# Generated by Django 5.2.14 on 2026-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0016_alter_competenciaauditoriaevento_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoqualidadecompetencia',
            name='nota_final_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nota final manual'),
        ),
        migrations.AddField(
            model_name='avaliacaoqualidadecompetencia',
            name='percentual_liberacao_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Percentual manual'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='coordenadora_pagamento_nome_manual',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome manual da coordenadora'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='diretora_pagamento_nome_manual',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome manual da diretora'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='gestor_pagamento_nome_manual',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome manual do gestor do contrato'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='subsecretario_pagamento_nome_manual',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nome manual do subsecretário'),
        ),
        migrations.AddField(
            model_name='competenciapagamento',
            name='valor_liberado_final_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor liberado final manual'),
        ),
    ]
